[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "finance_tracker"
version = "0.0.1"        
description = "Personal finance tracker with MongoDB"
requires-python = ">=3.8"

[tool.setuptools.packages.find]
where = ["src"]